version: 2

defaults: &defaults
  machine: true
  working_directory: ~/deciphernow/gm-data-sdk
  parallelism: 1
  shell: /bin/bash --login

jobs:
  cache:
    <<: *defaults
    steps:
      - checkout
      - run: mvn -version
      - run: rm -rf ~/.m2
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
            - cache-{{ .Branch }}-{{ checksum "pom.xml" }}
            - cache-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          key: cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
          paths:
            - "~/.m2"
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
            - cache-{{ .Branch }}-{{ checksum "pom.xml" }}
            - cache-{{ checksum "pom.xml" }}
      - run: mvn verify -DskipTests=true
  deploy:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - cache-{{ .Branch }}-{{ .Revision }}-{{ checksum "pom.xml" }}
            - cache-{{ .Branch }}-{{ checksum "pom.xml" }}
            - cache-{{ checksum "pom.xml" }}
      - run: PGP_RINGS="$(echo ${PGP_RINGS_ENCODED} | base64 --decode)" mvn deploy -P deploy -s settings.xml
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - cache:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - build:
          requires:
            - cache
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/
      - deploy:
          requires:
            - cache
            - build
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master